### ISSUE TITLE
下载RAD2-1.16.5-0.6时报错

### ISSUE THREAD

**Issue by shedya** [AnzhiZhang/CurseForgeModpackDownloader#2]
下载RAD2-1.16.5-0.6时报错
```
[2022-05-23 19:59:07] [INFO]: 获取模组下载链接（1/274）
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 700, in urlopen
  File "urllib3\connectionpool.py", line 994, in _prepare_proxy
  File "urllib3\connection.py", line 364, in connect
  File "urllib3\connection.py", line 499, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1070, in _create
  File "ssl.py", line 1341, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 440, in send
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='addons-ecs.forgesvc.net', port=443): Max retries exceeded with url: /api/v2/addon/250577/file/3190372/download-url (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 156, in <module>
  File "main.py", line 38, in get_download_urls
  File "utils\session.py", line 22, in get_download_url
  File "utils\session.py", line 19, in get
  File "requests\sessions.py", line 542, in get
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='addons-ecs.forgesvc.net', port=443): Max retries exceeded with url: /api/v2/addon/250577/file/3190372/download-url (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
[25912] Failed to execute script 'main' due to unhandled exception!

```

**Comment by AnzhiZhang** [comment]
网不好，重试即可

**Comment by shedya** [comment]
> 网不好，重试即可

我挂代理了 所以下载不了
